### PR TITLE
Fixes preRegisterCheck to cope with Directus 11x

### LINKED ISSUE #40: Not working after upgrade to Directus 11.0.1
Hi there,

it seems like the module is not loading in Directus 11.0.1 even though the extension is installed and enabled. It doesn't list in the settings screen though for me to enable it in the sidebar.

Anyone know how to fix this?

Cheers!

Kees.

### PR DESCRIPTION
**Pull request by keesvanbemmel**

### CODE REVIEW

**Comment by raffareis** [comment]
Confirmed, this fixes it. Made the change manually, button came back up.

**Review by raffareis — APPROVED** [review]
This works

**Comment by ithan** [comment]
@maltejur would it be possible to accept this merge request? Without it the extension does not work in Directus 11.x

**Comment by yvylol** [comment]
Hope it get merged soon

**Comment by maltejur** [comment]
Thanks for this, and sorry about my inactivity. Will prepare a new release right now.

**Comment by keesvanbemmel** [comment]
> Thanks for this, and sorry about my inactivity. Will prepare a new release right now.

Thanks for merging! And as a rule of thumb: never say sorry for inactivity on a free open source project ;) Thanks for all our efforts!

**Pull request merged**
